timezone: Europe/Rome
locale: it_IT.UTF-8
url: http://localhost:8888
title: Datasounds
description: "Data start to play..."
logo: logo.png
email: hello@datasounds.io
address: C.da Fonte Lappone, 86090 Pesche IS Italy
phone: "+39 0874404159"
links:
  facebook: datasounds
  twitter: thedatasounds
  linkedin: datasounds
authors:
  lead:
    rocoli:
      name: Rocco Oliveto
      role: Chief Executive Officer
      bio: Just a simple bio here...
      twitter: RoccoOliveto
      facebook: rocco.oliveto.1
      email: "rocco@datasound.it"
      pic: roccooliveto.jpg
    rpareschi:
      name: Remo Pareschi
      role: Chief Business Officer
      bio: Just a simple bio here...
      twitter: remo_pareschi
      facebook: remo.pareschi
      email: "remo@datasound.it"
      pic: remopareschi.jpg
    mattmezza:
      name: Matteo Merola
      role: Chief Technical Officer
      bio: "Just a regulard guy, but with superpowers..."
      linkedin: matteomerola
      twitter: _mattmezza_
      facebook: matteo.merola
      email: "matteo@datasound.it"
      pic: matt.jpeg
    s.scalabrino:
      name: Simone Scalabrino
      role: Chief Scientific Officer
      bio: Just a simple bio here...
      twitter: SimonScalabrino
      facebook: simone.scalabrino
      email: "simone@datasound.it"
      pic: simone.jpg
  scientists:
    vito.chiuri:
      name: Vito Chiuri
      role: Chief Operation Officer
      bio: Just a simple bio here...
      twitter: 
      facebook: 
      email: "vito@datasound.it"
      pic: sconosciuto.jpg
    damian.tamburri:
      name: Damian Andrew Tamburri
      role: Chief Financial Officer
      bio: Just a simple bio here...
      twitter: maelstromdat
      facebook: damian.tamburri
      linkedin: maelstrom
      email: "damian@datasound.it"
      pic: damian.jpg
    stefano.dallapalma:
      name: Stefano Dalla Palma
      role: Project Manager
      bio: Just a simple bio here...
      linkedin: stefanodallapalma
      twitter: stefanodp0
      email: "stefano@datasound.it"
      pic: stefano.jpg
theme: datasounds
posts:
  dir: posts
  perpage: 5
pages:
  dir: pages
navigation:
  - {url: "/blog", label: Blog}
