timezone: Europe/Rome
locale: it_IT.UTF-8
url: http://datasound.dev/
title: Datasound
description: "Data start to play..."
logo: logo.png
authors:
  admin:
    name: Matteo Merola
    bio: "Just a regulard guy, but with superpowers..."
    instagram: chiamamimatt
    facebook: matteo.merola
    email: "mattmezza@gmail.com"
    pic: matt.jpeg
  id-of-an-author:
    name: John Doe
    bio: Just a simple bio here...
    twitter: jhonny
    facebook: john.doe
    email: "john@doe.com"
theme: default
posts:
  dir: posts
  perpage: 5
pages:
  dir: pages
navigation:
  - {url: "/", label: Home}
  - {url: "/shortcode",label: Sample page}
