timezone: Europe/Rome
locale: it_IT.UTF-8
url: https://www.datasound.it
title: datasound
description: "Data start to play..."
logo: logo.png
email: hello@datasound.it
address: C.da Fonte Lappone, 86090 Pesche IS Italy
phone: "+39 0874404159"
links:
  facebook: datasounds
  twitter: thedatasounds
  linkedin: datasounds
authors:
  lead:
    rocoli:
      name: Rocco Oliveto
      role: Chief Executive Officer
      bio: Just a simple bio here...
      twitter: RoccoOliveto
      facebook: rocco.oliveto.1
      email: "rocco@datasound.it"
      pic: roccooliveto.jpg
    rpareschi:
      name: Remo Pareschi
      role: Chief Business Officer
      bio: Just a simple bio here...
      twitter: remo_pareschi
      facebook: remo.pareschi
      email: "remo@datasound.it"
      pic: remopareschi.jpg
    mattmezza:
      name: Matteo Merola
      role: Chief Technical Officer
      bio: "Just a regulard guy, but with superpowers..."
      linkedin: matteomerola
      twitter: _mattmezza_
      facebook: matteo.merola
      email: "matteo@datasound.it"
      pic: matt.jpeg
    s.scalabrino:
      name: Simone Scalabrino
      role: Chief Scientific Officer
      bio: Just a simple bio here...
      twitter: SimonScalabrino
      facebook: simone.scalabrino
      email: "simone@datasound.it"
      pic: simone.jpg
  developers:
    stefano.dallapalma:
      name: Stefano <br /> Dalla Palma
      role: Research Assistant
      bio: Just a simple bio here...
      twitter:
      facebook: stefano.d.palma
      email: "stefano.dallapalma@datasound.it"
      pic: stefano.jpg
theme: datasounds
posts:
  dir: posts
  perpage: 5
pages:
  dir: pages
navigation:
  - {url: "/blog", label: Blog}
